# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-16.04'

trigger:
- master

strategy:
  matrix:
    base:
      containerImage: r-base:latest
    tidyverse:
      containerImage: rocker/tidyverse:latest

container: $[ variables['containerImage'] ]

steps:
  - script: |
      printenv
      R
      install.packages(c("lintr", "covr"), repos = "http://cran.us.r-project.org")
      lintr::lint_package()
      library(covr)
      covr::coveralls()
      codecov()