# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    r-devel:
      containerImage: r-devel:latest
    r-base:
      containerImage: r-base:latest

steps:
- task: Docker@0
  displayName: 'Used R-base docker image to build R package'
  inputs: 
    containerRegistryType: "Container Registry"
    action: "Run an image"
    imageName: r-base
    containerCommand: 'R CMD INSTALL $PKG_TARBALL;'

- script: Rscript -e 'lintr::lint_package()'

- script: Rscript -e 'library(covr);covr::coveralls();codecov()'
    