# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

strategy:
  matrix:
    r-devel:
      containerImage: r-devel:latest
    r-base:
      containerImage: r-base:latest

container: $[ variables['containerImage'] ]

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    printenv
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
