# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-16.04'

trigger:
- master

strategy:
  matrix:
    base:
      containerImage: r-base:latest
    tidyverse:
      containerImage: rocker/tidyverse:latest

container: $[ variables['containerImage'] ]

steps:
  - script: |
      printenv
      cd /usr/local/lib/R
      sudo chmod o+w site-library
      Rscript -e 'install.packages(c("lintr", "covr"), repos = "http://cran.us.r-project.org")'
      Rscript -e 'lintr::lint_package()'
      Rscript -e 'library(covr)'
      Rscript -e 'covr::coveralls()'
      Rscript -e 'codecov()'