version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    working_directory: ~/main
    docker:
    - image: rocker/tidyverse:latest
    environment:
      NOT_CRAN: true
      CC_TEST_REPORTER_ID: 7f6f541be829a83a1b5837e73fd74c27863326cbf6d9e5698c6d408c983c45e4
    steps:
      - checkout
      #- restore_cache:
      #    keys:
      #      - deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}-{{ checksum ".circleci/config.yml" }}
      #      - deps1-{{ .Branch }}
      #      - deps1-
      - run:
          command: |
            R -e "devtools::install_deps(dependencies = TRUE)"
            R -e "install.packages('lintr', dependencies = TRUE)"
            R -e "install.packages('covr', dependencies = TRUE)"
      - run:
          no_output_timeout: 30m
          command: |
            R -e 'devtools::check(run_dont_test = TRUE)'
      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "/usr/local/lib/R/site-library"
      #- run:
      # https://docs.codeclimate.com/docs/circle-ci-test-coverage-example
      #    name: Setup Code Climate test-reporter
      #    command: |
      #    # download test reporter as a static binary
      #      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #      chmod +x ./cc-test-reporter
      - run:
          no_output_timeout: 20m
          command: |
            mkdir /root/main/artifacts
            R -e "devtools::install()"
            R -e "lintr::lint_package(); library(covr); covr::codecov()"
      - store_artifacts:
          path: /root/main/artifacts/
      - codecov/upload:
          token: 'd9508b8e-7bc1-4212-a361-86d64a361045'
destination: artifacts